package mypals.ml.config;
import com.terraformersmc.modmenu.api.ConfigScreenFactory;
import com.terraformersmc.modmenu.api.ModMenuApi;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;

import java.awt.*;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import dev.isxander.yacl3.gui.image.ImageRenderer;
import mypals.ml.ExplosionVisualizer;
import mypals.ml.explotionManage.FakeExplosion;
import net.minecraft.client.MinecraftClient;
import net.minecraft.text.Text;
import net.minecraft.util.Colors;
import net.minecraft.util.Formatting;
import net.minecraft.util.Identifier;

import static mypals.ml.ExplosionVisualizer.UpadteSettings;


public class ModMenuIntegration implements ModMenuApi {
    public static boolean test = false;
    public static int intSlider = 5;
    public static int Xmin = 0, Ymin = 0, Zmin = 0;
    public static int Xmax = 16, Ymax = 16, Zmax = 16;
    public static int LayerMin = 0, LayerMax = 100;


    @Override
    public ConfigScreenFactory<?> getModConfigScreenFactory() {
        MinecraftClient client = MinecraftClient.getInstance();
        var instance = VisualizerConfig.HANDLER;
        return parentScreen -> YetAnotherConfigLib.createBuilder()
                .title(Text.translatable("config.title.explosion_visualizer"))
                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("config.category.explosion_visualizer"))

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("config.group.renders"))
                                //.description(OptionDescription.of(Text.literal("Main mod features")))
                                .description(OptionDescription.createBuilder()
                                        .text(Text.translatable("config.description.main_features"))
                                        .image(ExplosionVisualizer.id("textures/all-explosives.png"), 192, 108)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.option.main_render"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.option.description.main_render").formatted(Formatting.YELLOW))
                                                .image(ExplosionVisualizer.id("textures/main-render.png"), 192, 108)
                                                .build()
                                        )
                                        .binding(true, () -> instance.instance().showInfo, bool -> instance.instance().showInfo = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.option.block_destruction"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.option.description.block_destruction"))
                                                .image(ExplosionVisualizer.id("textures/block-destruction.png"), 192, 108)
                                                .build()
                                        )
                                        .binding(false, () -> instance.instance().showBlockDestroyInfo, bool -> instance.instance().showBlockDestroyInfo = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.option.block_detection_ray"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.option.description.block_detection_ray"))
                                                .image(ExplosionVisualizer.id("textures/ray.png"), 192, 108)
                                                .build()
                                        )
                                        .binding(false, () -> instance.instance().showExplosionBlockDamageRayInfo, bool -> instance.instance().showExplosionBlockDamageRayInfo = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.option.sample_points"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.option.description.sample_points"))
                                                .image(ExplosionVisualizer.id("textures/sample-points.png"), 192, 108)
                                                .build()
                                        )
                                        .binding(false, () -> instance.instance().showRayCastInfo, bool -> instance.instance().showRayCastInfo = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build())

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.option.explosion_damage"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.option.description.explosion_damage"))
                                                .image(ExplosionVisualizer.id("textures/damage.png"), 192, 108)
                                                .build()
                                        )
                                        .binding(false, () -> instance.instance().showDamageInfo, bool -> instance.instance().showDamageInfo = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build())

                                .build())

                        .build())

                .title(Text.translatable("config.title.settings"))
                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("config.category.settings"))
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("config.group.block_detection_ray_settings"))
                                .description(OptionDescription.createBuilder()
                                        .text(Text.translatable("config.description.block_detection_ray_settings"))
                                        .image(ExplosionVisualizer.id("textures/example.png"), 500, 500)
                                        .build()
                                )
                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.option.x_min"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.x_min")))
                                        .binding(0, () -> instance.instance().Xmin, v -> instance.instance().Xmin = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.option.x_max"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.x_max")))
                                        .binding(16, () -> instance.instance().Xmax, v -> instance.instance().Xmax = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.option.y_min"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.y_min")))
                                        .binding(0, () -> instance.instance().Ymin, v -> instance.instance().Ymin = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.option.y_max"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.y_max")))
                                        .binding(16, () -> instance.instance().Ymax, v -> instance.instance().Ymax = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.option.z_min"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.z_min")))
                                        .binding(0, () -> instance.instance().Zmin, v -> instance.instance().Zmin = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.option.z_max"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.z_max")))
                                        .binding(16, () -> instance.instance().Zmax, v -> instance.instance().Zmax = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 16)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.option.invert"))
                                        .description(OptionDescription.createBuilder()
                                                .text(Text.translatable("config.option.description.invert"))
                                                .image(ExplosionVisualizer.id("textures/invert.png"), 192, 108)
                                                .build())
                                        .binding(false, () -> instance.instance().Invert, bool -> instance.instance().Invert = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.option.layer_min"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.layer_min")))
                                        .binding(0, () -> instance.instance().LayerMin, v -> instance.instance().LayerMin = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 100)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Integer>createBuilder()
                                        .name(Text.translatable("config.option.layer_max"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.layer_max")))
                                        .binding(100, () -> instance.instance().LayerMax, v -> instance.instance().LayerMax = v)
                                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                                .range(0, 100)
                                                .step(1)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("config.option.block_detection_ray_icon"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.block_detection_ray_icon")))
                                        .binding("⧈", () -> instance.instance().BlockDetectionRayIcon, v -> instance.instance().BlockDetectionRayIcon = v)
                                        .controller(StringControllerBuilder::create)
                                        .build()
                                )

                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("config.option.block_detection_ray_icon_size"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.block_detection_ray_icon_size")))
                                        .binding(0.005F, () -> instance.instance().BlockDetectionRayIconSize, v -> instance.instance().BlockDetectionRayIconSize = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .range(0F, 0.1F)
                                                .step(0.005F)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )

                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.option.render_with_alpha"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.render_with_alpha")))
                                        .binding(false, () -> instance.instance().EnableAlpha, bool -> instance.instance().EnableAlpha = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build()
                                )
                                        .option(Option.<Boolean>createBuilder()
                                                .name(Text.translatable("config.option.see_Throw"))
                                                .description(OptionDescription.of(Text.translatable("config.option.description.see_Throw")))
                                                .binding(false, () -> instance.instance().BlockDetectionRaySeeThrow, bool -> instance.instance().BlockDetectionRaySeeThrow = bool)
                                                .controller(BooleanControllerBuilder::create)
                                                .build()
                                        )

                        .build()
                        )

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("config.option.block_destruction_render_settings"))
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("config.option.block_destruction_render_color"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.block_destruction_render_color")))
                                        .binding(Color.YELLOW, () -> instance.instance().BlockDestroyIconColor, v -> instance.instance().BlockDestroyIconColor = v)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build()
                                )
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("config.option.block_destruction_render_icon"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.block_destruction_render_icon")))
                                        .binding("!", () -> instance.instance().BlockDestroyIcon, v -> instance.instance().BlockDestroyIcon = v)
                                        .controller(StringControllerBuilder::create)
                                        .build()
                                )
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("config.option.block_destruction_render_icon_size"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.block_destruction_render_icon_size")))
                                        .binding(0.05F, () -> instance.instance().BlockDestroyIconSize, v -> instance.instance().BlockDestroyIconSize = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .range(0F, 0.2F)
                                                .step(0.05F)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.option.see_Throw"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.see_Throw")))
                                        .binding(true, () -> instance.instance().BlockDestroyIconSeeThrow, bool -> instance.instance().BlockDestroyIconSeeThrow = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build()
                                )
                                .build()
                        )

                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("config.option.entity_sample_point_render_settings"))
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("config.option.entity_sample_point_safe_color"))
                                        .binding(Color.GREEN, () -> instance.instance().EntitySamplePoion_Safe_IconColor, v -> instance.instance().EntitySamplePoion_Safe_IconColor = v)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build()
                                )
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("config.option.entity_sample_point_safe_icon"))
                                        .binding("√", () -> instance.instance().EntitySamplePoion_Safe_Icon, v -> instance.instance().EntitySamplePoion_Safe_Icon = v)
                                        .controller(StringControllerBuilder::create)
                                        .build()
                                )
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("config.option.entity_sample_point_danger_color"))
                                        .binding(Color.RED, () -> instance.instance().EntitySamplePoion_Danger_IconColor, v -> instance.instance().EntitySamplePoion_Danger_IconColor = v)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build()
                                )
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("config.option.entity_sample_point_danger_icon"))
                                        .binding("X", () -> instance.instance().EntitySamplePoion_Danger_Icon, v -> instance.instance().EntitySamplePoion_Danger_Icon = v)
                                        .controller(StringControllerBuilder::create)
                                        .build()
                                )
                                .option(Option.<Color>createBuilder()
                                        .name(Text.translatable("config.option.entity_sample_point_blocked_color"))
                                        .binding(Color.MAGENTA, () -> instance.instance().EntitySamplePoion_Blocked_IconColor, v -> instance.instance().EntitySamplePoion_Blocked_IconColor = v)
                                        .controller(opt -> ColorControllerBuilder.create(opt)
                                                .allowAlpha(true))
                                        .build()
                                )
                                .option(Option.<String>createBuilder()
                                        .name(Text.translatable("config.option.entity_sample_point_blocked_icon"))
                                        .binding("❖", () -> instance.instance().EntitySamplePoion_Blocked_Icon, v -> instance.instance().EntitySamplePoion_Blocked_Icon = v)
                                        .controller(StringControllerBuilder::create)
                                        .build()
                                )
                                .option(Option.<Float>createBuilder()
                                        .name(Text.translatable("config.option.entity_sample_point_icon_size"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.entity_sample_point_icon_size")))
                                        .binding(0.01F, () -> instance.instance().EntitySamplePoionIconSize, v -> instance.instance().EntitySamplePoionIconSize = v)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .range(0F, 0.03F)
                                                .step(0.01F)
                                                .formatValue(val -> Text.literal(val + "")))
                                        .build()
                                )
                                .option(Option.<Boolean>createBuilder()
                                        .name(Text.translatable("config.option.see_Throw"))
                                        .description(OptionDescription.of(Text.translatable("config.option.description.see_Throw")))
                                        .binding(true, () -> instance.instance().EntitySamplePointSeeThrow, bool -> instance.instance().EntitySamplePointSeeThrow = bool)
                                        .controller(BooleanControllerBuilder::create)
                                        .build()
                                )

                                .build()
                        )
                        .build()
                )
                .save(() -> {
                    instance.save();
                    UpadteSettings();
                })
                .build()
        .generateScreen(parentScreen);
    }
}
